### ISSUE TITLE
Build failed v2.2.3 due to openssl error 

### ISSUE THREAD

**Issue by nwshane** [rbenv/ruby-build#850]
Command `rbenv install 2.2.3` causes this error:

```
.....
compiling ossl_pkey_rsa.c
compiling strscan.c
compiling udpsocket.c
compiling unixsocket.c
compiling unixserver.c
compiling ossl_rand.c
linking shared-object strscan.bundle
compiling option.c
compiling ancdata.c
compiling ossl_ssl.c
ossl_ssl.c:125:5: error: use of undeclared identifier 'TLSv1_2_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_2),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:106:1: note: expanded from here
TLSv1_2_method
^
ossl_ssl.c:126:5: error: use of undeclared identifier 'TLSv1_2_server_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_2_server),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:106:1: note: expanded from here
TLSv1_2_server_method
^
ossl_ssl.c:127:5: error: use of undeclared identifier 'TLSv1_2_client_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_2_client),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:106:1: note: expanded from here
TLSv1_2_client_method
^
ossl_ssl.c:131:5: error: use of undeclared identifier 'TLSv1_1_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_1),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:106:1: note: expanded from here
TLSv1_1_method
^
ossl_ssl.c:132:5: error: use of undeclared identifier 'TLSv1_1_server_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_1_server),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:106:1: note: expanded from here
TLSv1_1_server_method
^
compiling raddrinfo.c
ossl_ssl.c:133:5: error: use of undeclared identifier 'TLSv1_1_client_method'
    OSSL_SSL_METHOD_ENTRY(TLSv1_1_client),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:106:1: note: expanded from here
TLSv1_1_client_method
^
ossl_ssl.c:210:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:115:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:1127:13: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
            if (rc = SSL_shutdown(ssl))
                ~~~^~~~~~~~~~~~~~~~~~~
ossl_ssl.c:1127:13: note: place parentheses around the assignment to silence this warning
            if (rc = SSL_shutdown(ssl))
                   ^
                (                     )
ossl_ssl.c:1127:13: note: use '==' to turn this assignment into an equality comparison
            if (rc = SSL_shutdown(ssl))
                   ^
                   ==
ossl_ssl.c:2194:23: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:115:14) []'
    ary = rb_ary_new2(numberof(ossl_ssl_method_tab));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2195:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:115:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
1 warning and 9 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling ifaddr.c
installing default socket libraries
compiling init.c
compiling constants.c
linking shared-object socket.bundle
linking shared-object ripper.bundle
make: *** [build-ext] Error 2
```
- Mac OS X 10.11.1
- rbenv 0.4.0
- ruby-build 20151028
- Output of `brew list openssl`:

```
/usr/local/Cellar/openssl/1.0.2d_1/bin/c_rehash
/usr/local/Cellar/openssl/1.0.2d_1/bin/openssl
/usr/local/Cellar/openssl/1.0.2d_1/include/openssl/ (75 files)
/usr/local/Cellar/openssl/1.0.2d_1/lib/libcrypto.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2d_1/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2d_1/lib/engines/ (12 files)
/usr/local/Cellar/openssl/1.0.2d_1/lib/pkgconfig/ (3 files)
/usr/local/Cellar/openssl/1.0.2d_1/lib/ (4 other files)
/usr/local/Cellar/openssl/1.0.2d_1/share/man/ (1535 files)
```

**Comment by mislav** [comment]
Thanks for all the info! Unfortunately, I have no idea why this is failing. Maybe the openssl version from Homebrew is too new to work with 2.2.3?

The error is similar to what @chaak20 got in https://github.com/rbenv/ruby-build/issues/736#issuecomment-84757044

**Comment by diop** [comment]
Mine's causing this error as well:

17:25 ~  $ rbenv install 2.2.3
Downloading openssl-1.0.1q.tar.gz...
-> https://www.openssl.org/source/openssl-1.0.1q.tar.gz
error: failed to download openssl-1.0.1q.tar.gz

BUILD FAILED (OS X 10.11.2 using ruby-build 20151028-28-g59453d4)

**Comment by mislav** [comment]
@diop Yours seems like a network issue. Have you retried later or on a different network?

**Comment by diop** [comment]
@mislav Ah! Could be. I will definitely try on a different network. Thanks for the tip.

**Comment by mislav** [comment]
@nwshane Do you still have the original issue? I haven't heard of any similar reports since.

**Comment by nwshane** [comment]
@mislav I'm on vacation, so I can check when I get back to work in a few days. Now that 2.3 has been released, I actually don't have a need for 2.2.3 anymore, but if you want I can try to reproduce this issue.

**Comment by joshuachestang** [comment]
happening with rvm install too.

**Comment by ckoppelman** [comment]
I was having this issue and investigated openssl.  Turns out although I had `brew`'ed openssl 1.0.2j, the linked version was 0.9.8zg.  Running `brew unlink openssl098` fixed the problem and allowed me to install Rubies at whim.

**Comment by mislav** [comment]
Closing as outdated
