### ISSUE TITLE
ree-1.8.7-2011.03 fails to build with openssl 1.0.0

### ISSUE THREAD

**Issue by be9** [rbenv/ruby-build#75]
rbenv install ree-1.8.7-2011.03

```
ossl_ssl.c:101:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:101:5: warning: (near initialization for 'ossl_ssl_method_tab[0].func') [enabled by default]
ossl_ssl.c:102:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:102:5: warning: (near initialization for 'ossl_ssl_method_tab[1].func') [enabled by default]
ossl_ssl.c:103:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:103:5: warning: (near initialization for 'ossl_ssl_method_tab[2].func') [enabled by default]
ossl_ssl.c:104:1: error: 'SSLv2_method' undeclared here (not in a function)
ossl_ssl.c:105:1: error: 'SSLv2_server_method' undeclared here (not in a function)
ossl_ssl.c:106:1: error: 'SSLv2_client_method' undeclared here (not in a function)
ossl_ssl.c:107:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:107:5: warning: (near initialization for 'ossl_ssl_method_tab[6].func') [enabled by default]
ossl_ssl.c:108:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:108:5: warning: (near initialization for 'ossl_ssl_method_tab[7].func') [enabled by default]
ossl_ssl.c:109:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:109:5: warning: (near initialization for 'ossl_ssl_method_tab[8].func') [enabled by default]
ossl_ssl.c:110:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:110:5: warning: (near initialization for 'ossl_ssl_method_tab[9].func') [enabled by default]
ossl_ssl.c:111:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:111:5: warning: (near initialization for 'ossl_ssl_method_tab[10].func') [enabled by default]
ossl_ssl.c:112:5: warning: initialization from incompatible pointer type [enabled by default]
ossl_ssl.c:112:5: warning: (near initialization for 'ossl_ssl_method_tab[11].func') [enabled by default]
ossl_ssl.c: In function 'ossl_ssl_get_cipher':
ossl_ssl.c:1224:12: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
make[1]: *** [ossl_ssl.o] Error 1
make[1]: Leaving directory `/tmp/ruby-build.20111026110110.14103/ruby-enterprise-1.8.7-2011.03/source/ext/openssl'
make: *** [all] Error 1
```

This by itself is a known issue, see http://bit.ly/sa4TAo

But there's no way to pass a patch to ruby-build to overcome this.
