### ISSUE TITLE
MRI 1.8.7-p375 fails to build on OSX Yosemite; 1.8.7-p249 succeeds

### ISSUE THREAD

**Issue by RUN-CMD** [rbenv/ruby-build#922]
Building ruby MRI 1.8.7-p375 fails, however building ruby MRI 1.8.7-p249 succeeds.

Here's the 1.8.7-p375 failure:

```
$ time ruby-build 1.8.7-p375 ~/.rubies/1.8.7-p375
Checking out http://svn.ruby-lang.org/repos/ruby/branches/ruby_1_8_7...
Installing ruby-1.8.7-p375...
Installed ruby-1.8.7-p375 to /Users/ksandwich/.rubies/1.8.7-p375

Downloading rubygems-1.6.2.tgz...
-> https://dqw8nmjcqpjn7.cloudfront.net/cb5261818b931b5ea2cb54bc1d583c47823543fcf9682f0d6298849091c1cea7
Installing rubygems-1.6.2...

BUILD FAILED (OS X 10.10.5 using ruby-build 20160130)

Inspect or clean up the working tree at /var/folders/qy/9ljgg_h14mg1rmq5hdrkpkdr0000gp/T/ruby-build.20160325110214.45135
Results logged to /var/folders/qy/9ljgg_h14mg1rmq5hdrkpkdr0000gp/T/ruby-build.20160325110214.45135.log

Last 10 log lines:
/var/folders/qy/9ljgg_h14mg1rmq5hdrkpkdr0000gp/T/ruby-build.20160325110214.45135/rubygems-1.6.2 /var/folders/qy/9ljgg_h14mg1rmq5hdrkpkdr0000gp/T/ruby-build.20160325110214.45135 ~/agent
dyld: lazy symbol binding failed: Symbol not found: _rb_intern2
  Referenced from: /Users/ksandwich/.gem/ruby/1.9.3/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_intern2
  Referenced from: /Users/ksandwich/.gem/ruby/1.9.3/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

/usr/local/bin/ruby-build: line 554: 54870 Trace/BPT trap: 5       "$RUBY_BIN" setup.rb

real    1m18.405s
```

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

And here's the 1.8.7-p249 success, shortly afterwards on the same config:

```
$ time ruby-build 1.8.7-p249 ~/.rubies/1.8.7-p249
Downloading ruby-1.8.7-p249.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p249.tar.bz2
Installing ruby-1.8.7-p249...
Installed ruby-1.8.7-p249 to /Users/ksandwich/.rubies/1.8.7-p249

Downloading rubygems-1.6.2.tgz...
-> https://dqw8nmjcqpjn7.cloudfront.net/cb5261818b931b5ea2cb54bc1d583c47823543fcf9682f0d6298849091c1cea7
Installing rubygems-1.6.2...
Installed rubygems-1.6.2 to /Users/ksandwich/.rubies/1.8.7-p249


real    1m14.759s
```

Hope this helps anyone who is trying to build any 1.8.7; try a different patch level and you may have some good fortune :game_die:

**Comment by hsbt** [comment]
I can install `% CC=/usr/local/bin/gcc-4.2 rbenv install 1.8.7-p375` with apple-gcc45 on homebrew/dups
